Feature/task2
Kolenchitssi/HiQo_JavaScript pull request #3
Opened 2021-07-21 10:50 UTC by Kolenchitssi

Task2

2021-07-22 13:01 UTC, irina-chernik requested changes

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +    return newArr;
consider optimizing and using one return statement - you initialize newArr as empty anyway

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +      } else {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
else statement is extra here, look how slice works if end value is greater

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +      if (arr2.indexOf(element) === -1) {
use other element for check if array includes element
you don't really need an element position here

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +  if (!arr) return [];
function that returns element postion (i.e number) shouldn't return empty array in negative scenario

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +  if (typeof item === 'function') {
try using less code

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +  let newArr = arr;
try simplifying code
it can be written even in one line
look up for array methods that check if element passes function conditions

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +  let mySet = new Set(arr);
shorten code

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +/* Task 7 */
implement task7 or task8 without using corresponding array method

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +  if (!object1 || !object2) return false;
add empty lines between logical blocks of the function

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +    if (Array.isArray(item) === false || item.length !== 2) {
again think about simplifying code
no need to loop through array twice

2021-07-22 13:01 UTC, irina-chernik commented on tasks/task2.js
> +    item = arr[i];
use destructuring assignment for readability

2021-07-23 05:27 UTC, Kolenchitssi commented on tasks/task2.js
> +    return newArr;
Completed

2021-07-23 05:40 UTC, Kolenchitssi commented on tasks/task2.js
> +      } else {
Completed

2021-07-23 05:56 UTC, Kolenchitssi commented on tasks/task2.js
> +      if (arr2.indexOf(element) === -1) {
Competed, use includes().

2021-07-23 06:00 UTC, Kolenchitssi commented on tasks/task2.js
> +  if (!arr) return [];
fixed it: 
if (!arr) return false;

2021-07-23 06:16 UTC, Kolenchitssi commented on tasks/task2.js
> +  if (typeof item === 'function') {
completed

2021-07-23 06:29 UTC, Kolenchitssi commented on tasks/task2.js
> +  let mySet = new Set(arr);
fixed it: 

function uniq(arr) {
  if (Array.isArray(arr) === false) return [];
  return Array.from(new Set(arr));
}

2021-07-23 06:34 UTC, Kolenchitssi commented on tasks/task2.js
> +  if (!object1 || !object2) return false;
completed

2021-07-23 08:33 UTC, Kolenchitssi commented on tasks/task2.js
> +/* Task 7 */
Task7:
function every(arr, func) {
  if (!arr || !func || arr.length === 0 || typeof func !== 'function') return false;
  return arr.every(func);
}

function every1(arr, func) {
  for (item of arr) {
    result = func(item);
    if (result === false) return false;
  }
  return true;
}

function every2(arr, func) {
  let itemTrue = true;
  arr.forEach((item) => {
    const result = func(item);
    if (result === false) itemTrue = false;
  });
  return itemTrue;
}
============================
task8:

function find(arr, func) {
  if (!arr || !func || arr.length === 0 || typeof func !== 'function') {
    return false;
  }
  return arr.find(func);
}

function find2(arr, func) {
  for (let item of arr) {
    const result = func(item);
    if (result === true) return item;
  }
  return null;
}

function find3(arr, func) {
  let itemTrue = null;
  arr.forEach((item) => {
    const result = func(item);
    if (result === true && !itemTrue) itemTrue = item;
  });
  return itemTrue;
}

2021-07-26 12:40 UTC, irina-chernik approved these changes

2021-07-26 13:32 UTC, merged